// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package public

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Header() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<header class=\"app-header bg-sky-100\"><div class=\"container mx-auto py-4 flex justify-between items-center\"><a href=\"/\" aria-label=\"home\"><figure class=\"app-header-logo flex justify-center items-center\"><img src=\"/media/Juniper-Logo-32.png\" alt=\"Juniper logo\" width=\"128\" height=\"128\"><figcaption class=\"text-emerald-800 font-bold text-5xl ml-4\">Juniper</figcaption></figure></a><nav class=\"flex gap-2 my-4 text-lg text-slate-600 font-bold\"><a href=\"/about\" class=\"hover:text-slate-900\">About</a> <a href=\"/dashboard\" class=\"hover:text-slate-900\">Dashboard</a></nav></div></header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
