// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.598
package public

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Header() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<header class=\"app-header bg-sky-100\"><div class=\"container mx-auto py-4 flex justify-between items-center\"><a href=\"/\" aria-label=\"home\"><figure class=\"app-header-logo flex justify-center items-center\"><img src=\"/media/Juniper-Logo-32.png\" alt=\"Juniper logo\" width=\"128\" height=\"128\"><figcaption class=\"text-emerald-800 font-bold text-5xl ml-4\">Juniper</figcaption></figure></a><nav class=\"flex gap-2 my-4 text-lg text-slate-600 font-bold\"><a href=\"/about\" class=\"hover:text-slate-900\">About</a> <a href=\"/dashboard\" class=\"hover:text-slate-900\">Dashboard</a></nav></div></header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
